"""Pre-Retrieval Eligibility Gate — decisione deterministica prima del retrieval."""

from .gate import (  # noqa: F401
    ADVERSARIAL_OR_CONTROL_INPUT, AMBIGUOUS_CASE_CONTEXT, CONTRADICTORY_CASE_CONTEXT,
    ELIGIBILITY_STATES, ELIGIBLE_FOR_RETRIEVAL, GATE_POLICY_VERSION,
    INSUFFICIENT_ONCOLOGY_CONTEXT, INVALID_INPUT, MISSING_REQUIRED_FIELDS,
    NON_ACTIONABLE_MEDICAL_INPUT, OUT_OF_SCOPE, EligibilityDecision, evaluate,
)
